---
# ONLY for Mutual TLS
apiVersion: v1
kind: Secret
metadata:
  name: sidecar-tls
  namespace: monitoring
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDizCCAzKgAwIBAgIUJ6LbJ9TyFkTJzkmuOA1ZBMtC868wCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI0MDMxNDA4NDMwMFoXDTI1
    MDMxNDA4NDMwMFowdzELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxRzBFBgNVBAMTPmt1YmUtcHJvbWV0aGV1cy1wcm9tZXRoZXVz
    LXRoYW5vcy5tb25pdG9yaW5nLnN2Yy5jbHVzdGVyLmxvY2FsMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEArnCN6eobzWQQc3EY/95Dpc86UCVW7LSU6bBv
    TI8vw10TTnXIj3ZnR3eWzEjjnvE2pnKnkPkqiIukZSOLu/j/mD36fAYMC4zjjnmR
    O/SttlkU+K7bcBjRUxou77OS19NEHKtbxY7/GrhqDe4ZfLaylPulD714nwYXB5Ne
    155bYWt4drU97IikSmx8dmWLdGm1TNUm8NifSlQChPA/XflN40pRk6me+Etpdab9
    nOu+mm6ej2BkbMtDR9VrRaCiuVa2Mg9eVphZe60MtEIiufuppsiP/2+VPzj6VAra
    FScag8I6u6aT1/E6xwOLEoZ37rDIWh4hDCH/EquSdYmvgpahOwIDAQABo4H9MIH6
    MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
    DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUV1Edhuh5lte3GhmkUKu9REjqYocwHwYD
    VR0jBBgwFoAUh6oa7kfHi2iATdO7X24Wo2agJXEwewYDVR0RBHQwcoI+a3ViZS1w
    cm9tZXRoZXVzLXByb21ldGhldXMtdGhhbm9zLm1vbml0b3Jpbmcuc3ZjLmNsdXN0
    ZXIubG9jYWyCMGt1YmUtcHJvbWV0aGV1cy1wcm9tZXRoZXVzLXRoYW5vcy5hbnRv
    bnB1dHJhLmNvbTAKBggqhkjOPQQDAgNHADBEAiAipK+UWvFRunfsFQGjjNfZkEfJ
    Z1E7ulxcM5HVWkKGvwIgQa94aa/vC0wUXnNJ6kTarl6HuK3mJCVXToME0rF2R0U=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEArnCN6eobzWQQc3EY/95Dpc86UCVW7LSU6bBvTI8vw10TTnXI
    j3ZnR3eWzEjjnvE2pnKnkPkqiIukZSOLu/j/mD36fAYMC4zjjnmRO/SttlkU+K7b
    cBjRUxou77OS19NEHKtbxY7/GrhqDe4ZfLaylPulD714nwYXB5Ne155bYWt4drU9
    7IikSmx8dmWLdGm1TNUm8NifSlQChPA/XflN40pRk6me+Etpdab9nOu+mm6ej2Bk
    bMtDR9VrRaCiuVa2Mg9eVphZe60MtEIiufuppsiP/2+VPzj6VAraFScag8I6u6aT
    1/E6xwOLEoZ37rDIWh4hDCH/EquSdYmvgpahOwIDAQABAoIBAF/4XJtMyW7+lm5s
    0qwyxFT85cAiSuh/kU3gW9trC4QYOP75nhYPtlKDYNuTXmebnc2FVttTuirVaOSb
    4czQ+Q3xS1Xgnc/c+3TvPRAXVVr1N6x5xxCtFrz5ssj9qtRCzz5WqG7QdVlmDDMN
    w8fxW97Lc8xtGWekGhd45L0LyoqVhRYs8JhlckbWYYxjbzJnTaImmQ/3OOIYbI1L
    iQ1Em3Xc7DTv4G0wa5PyTusETp+ykg6uNUYqg8qAgTz4gDI+Puxq/CsCUgr4BmLy
    4SvNWvxY8CSeSL9rfxzmJ0/aQT2q8kaOPEgqP5YiainVqrkxEMiXJdSiwaSXUinK
    hhxBnoECgYEA321WKtHFY71+aTtQDHRUOHC6Sw/KBtiOm4SS9V3V/YNproGH238l
    04kFYBLS1dmDHGVpbZ68c2zJraDeDmS8q7pVppQJlXZGo9a4pxrzJcIZ4XmNCy35
    i02mCWF5WMJPP1qQIoaB9LlY5Z5tY5RmjT8A+eCjPW00gKO0+91hj1MCgYEAx97t
    T9fdlq++eTmSYACpn435YW1ou14NUkkRh2VuDuw6mCbkUvjinMQlxRdzcAYmvSu5
    QCj/PBTzsAeGG2H1/h+ALLn91Oj8LtnWBVCos4luzllAONvhx7ATj4JO1d0UzpwZ
    i+mACBTPKrvzrCG/HMM+cwdPHO3vjWjjEq5pMXkCgYAWP477CJR9UBtMY0mfU94n
    GKKUYugdMmdQ+SyhHkz2x6U4aVGb+9dKbzSH0pgID3bM1xRehBYD8GtMzN4P1Nws
    xYtN4SPrLDHwkqskiLx5oBBvsWjoGhXlV0AXYwtwWTkG9/+uUHKUafh+NP5zkg18
    Ny/jsgjPTxaRULvu8KaMXQKBgA4STdbfNcSUHu7d9MY5hbesATCwyTzXxExUxJ0p
    sPPwAbgQlOaaiynKTXZwzjnG1Rdgaqxvtnh+aSGthe2LmgwIH7gGaC6DMK4DvCOn
    qBjrxhdVBUZ7hIvQg7AI1pAL/pkFOG83Q0JOZL93eBJYVeIqhM0IaLN6tPDZv5Lj
    IJjRAoGAVnXD3JlmvG4pocvtvgRi2Bi4WVETJHIevIOGeFo7bE41WLbq7mYidJSr
    2oqCLjw7vbfgtpvRINKyDTrO/Fuu/lUP6PZmzKVGLihsRCIkJxonjtqVLwxcv8jv
    csNPavaIDlTgjMxerXmVdOOHWYSFfxvvARLvitdQh8e7W+BAyAQ=
    -----END RSA PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB/DCCAaKgAwIBAgIULApIkXXJ3AoiWY1zJn1ZPzsNdxMwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI0MDMxNDA4MzkwMFoXDTI5
    MDMxMzA4MzkwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxGjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAEteg47Paf1qhdfmwe3RMGGh+WU/JpH+zrYUGgZgQg
    U2aRFxwi+Zil7VJbTrf12KwTwPJuJ4q2QiqX9Mwevf3eZ6NmMGQwDgYDVR0PAQH/
    BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQIwHQYDVR0OBBYEFIeqGu5Hx4togE3T
    u19uFqNmoCVxMB8GA1UdIwQYMBaAFIeqGu5Hx4togE3Tu19uFqNmoCVxMAoGCCqG
    SM49BAMCA0gAMEUCIQCNXn7yB4KeT12LA8UxndB+/W11AF38pn/3KogyoeTNLwIg
    NH419t6z+n7ofmiLvfUGq1p/MX1sjS4BmdpcklXulK0=
    -----END CERTIFICATE-----
